AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/ParameterLists:
  Exclude:
    - "lib/ticktick/resources/task_attributes.rb"
    - "lib/ticktick/resources/project_resource.rb"
    - "lib/ticktick/mcp/server/tools/project/create_project.rb"
    - "lib/ticktick/mcp/server/tools/project/update_project.rb"
    - "lib/ticktick/mcp/server/tools/task/create_task.rb"
